var buffer = '--------\n';
function Robo() {}
Robo.mova = function() {buffer += 'Mova\n';};
Robo.frenteBloqueada = function() {buffer += 'Frente bloqueada\n';};
Robo.frenteLivre = function() {buffer += 'Frente livre\n';};
Robo.esquerdaBloqueada = function() {buffer += 'Esquerda bloqueada\n';};
Robo.esquerdaLivre = function() {buffer += 'Esquerda livre\n';};
Robo.direitaBloqueada = function() {buffer += 'Direita bloqueada\n';};
Robo.direitaLivre = function() {buffer += 'Direita livre\n';};
Robo.naoProximoBip = function() {buffer += 'Não está próximo a bip\n';};
Robo.proximoBip = function() {buffer += 'Está próximo a bip\n';};
Robo.naoExistemBipsNaBolsa = function() {buffer += 'Não existem bips na bolsa\n';};
Robo.existemBipsNaBolsa = function() {buffer += 'Existem bips na bolsa\n';};
Robo.naoVoltadoNorte = function() {buffer += 'Não voltado ao Norte\n';};
Robo.voltadoNorte = function() {buffer += 'Voltado ao Norte\n';};
Robo.naoVoltadoSul = function() {buffer += 'Não voltado ao Sul\n';};
Robo.voltadoSul = function() {buffer += 'Voltado ao Sul\n';};
Robo.naoVoltadoOeste = function() {buffer += 'Não voltado ao Oeste\n';};
Robo.voltadoOeste = function() {buffer += 'Voltado ao Oeste\n';};
Robo.naoVoltadoLeste = function() {buffer += 'Não voltado ao Leste\n';};
Robo.voltadoLeste = function() {buffer += 'Voltado ao Leste\n';};
Robo.imprimeBuffer = function() {console.log(buffer);};
